version: "3.8"

services:

  api:
    build: 
      context: ./
      dockerfile: ./docker/api/Dockerfile
      target: dev
    container_name: tricentis-api
    command: npm run dev:server
    volumes:
      - ./api:/src/api
      - ./package.json:/src/package.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      


  
 